In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import pandas as pd

WARNING:tensorflow:From c:\Users\zw\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
file_path_ad_clean = "../Raw_data/pre_application_data_cleaned.csv"
application_df = pd.read_csv(file_path_ad_clean)
application_df.head()

,SK_ID_PREV,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,Y,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,Y,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,Y,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,Y,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# convert text to numbers for model
application_df = pd.get_dummies(application_df)

In [4]:
application_df.head(10)

,SK_ID_PREV,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,HOUR_APPR_PROCESS_START,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,...,PRODUCT_COMBINATION_Cash X-Sell: low,PRODUCT_COMBINATION_Cash X-Sell: middle,PRODUCT_COMBINATION_POS household with interest,PRODUCT_COMBINATION_POS household without interest,PRODUCT_COMBINATION_POS industry with interest,PRODUCT_COMBINATION_POS industry without interest,PRODUCT_COMBINATION_POS mobile with interest,PRODUCT_COMBINATION_POS mobile without interest,PRODUCT_COMBINATION_POS other with interest,PRODUCT_COMBINATION_POS others without interest
0,2030495,1730.430,17145.0,17145.0,0.0,17145.0,15,1,0.0,0.182832,...,False,False,False,False,False,False,True,False,False,False
1,2802425,25188.615,607500.0,679671.0,NaN,607500.0,11,1,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
2,2523466,15060.735,112500.0,136444.5,NaN,112500.0,11,1,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
3,2819243,47041.335,450000.0,470790.0,NaN,450000.0,7,1,NaN,NaN,...,False,True,False,False,False,False,False,False,False,False
4,1784265,31924.395,337500.0,404055.0,NaN,337500.0,9,1,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
5,1383531,23703.930,315000.0,340573.5,NaN,315000.0,8,1,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
6,1715995,11368.620,270000.0,335754.0,NaN,270000.0,7,1,NaN,NaN,...,True,False,False,False,False,False,False,False,False,False
7,2257824,13832.775,211500.0,246397.5,NaN,211500.0,10,1,NaN,NaN,...,False,True,False,False,False,False,False,False,False,False
8,2330894,12165.210,148500.0,174361.5,NaN,148500.0,15,1,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
9,1397919,7654.860,53779.5,57564.0,0.0,53779.5,15,1,0.0,NaN,...,False,False,False,True,False,False,False,False,False,False

In [5]:
#seperate feature and target
features = application_df.drop('NAME_CONTRACT_STATUS',axis=1).values
target = application_df['NAME_CONTRACT_STATUS'].values

In [6]:
X = features
y = target
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 5)

In [7]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num_input_features = len(X_train_scaled[0])
nodes_layer1 = 80
nodes_layer2 = 30
nodes_layer3 = 1

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = nodes_layer1, input_dim = num_input_features, activation ="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = nodes_layer2, activation ="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units = nodes_layer3, activation ="sigmoid"))
# Check the structure of the model
nn.summary()

WARNING:tensorflow:From c:\Users\zw\anaconda3\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                12720

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 15181 (59.30 KB)
Trainable params: 15181 (59.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [9]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

WARNING:tensorflow:From c:\Users\zw\anaconda3\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [10]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=20)

Epoch 1/20
WARNING:tensorflow:From c:\Users\zw\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\zw\anaconda3\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

31732/31732 [==============================] - 19s 593us/step - loss: 0.5204 - accuracy: 0.7853
Epoch 2/20
31732/31732 [==============================] - 19s 584us/step - loss: 0.5204 - accuracy: 0.7853
Epoch 3/20
31732/31732 [==============================] - 19s 591us/step - loss: 0.5203 - accuracy: 0.7853
Epoch 4/20
31732/31732 [==============================] - 19s 583us/step - loss: 0.5203 - accuracy: 0.7853
Epoch 5/20
31732/31732 [==============================] - 19s 592us/step - loss: 0.5203 - accuracy: 0.7853
Epoch 6/20
31732/31732 [==============================] - 19s 598us/step - loss: 0.5203 - accuracy: 0.7853
Epoch 7/20
31732/31732 [==============================] - 19s 588us/step - loss: 0.5203 - accuracy: 0.7853
Epoch 8/20
31732/31732 [==============================] - 19s 598us/step - loss: 0.5203 - accuracy: 0.7853
Epoch 9/20
31732/31732 [==============================] - 19s 591us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 10/20
31732/31732 [==============================] - 19s 591us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 11/20
31732/31732 [==============================] - 19s 592us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 12/20
31732/31732 [==============================] - 19s 587us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 13/20
31732/31732 [==============================] - 19s 587us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 14/20
31732/31732 [==============================] - 19s 593us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 15/20
31732/31732 [==============================] - 19s 586us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 16/20
31732/31732 [==============================] - 19s 587us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 17/20
31732/31732 [==============================] - 19s 600us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 18/20
31732/31732 [==============================] - 19s 608us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 19/20
31732/31732 [==============================] - 19s 598us/step - loss: 0.5202 - accuracy: 0.7853
Epoch 20/20
31732/31732 [==============================] - 19s 601us/step - loss: 0.5202 - accuracy: 0.7853

In [11]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

10578/10578 - 5s - loss: 0.5201 - accuracy: 0.7854 - 5s/epoch - 442us/step
Loss: 0.5201032757759094, Accuracy: 0.7853580713272095

In [12]:
nn.save('./trained_models/pre_app_model.h5')

c:\Users\zw\anaconda3\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(